"""init migration

Revision ID: f08747241435
Revises: 
Create Date: 2025-01-14 22:25:27.620229

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f08747241435"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
